// INPUT TYPES
export const NEW_INPUT = 'NEW_INPUT';
export const SET_INPUT = 'SET_INPUT';
export const UPDATE_INPUT = 'UPDATE_INPUT';

// AUTH TYPES
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';

// DATA TYPES
export const FETCH_DATA = 'FETCH_DATA';

// OVERVIEW TYPES
export const SET_OVERVIEW = 'SET_OVERVIEW';
export const UPDATE_OVERVIEW_DETAIL = 'UPDATE_OVERVIEW_DETAIL';

// WISHLIST TYPES
export const SET_WISHLIST = 'SET_WISHLIST';
export const NEW_WISHLIST = 'NEW_WISHLIST';
export const ADD_WISHLIST_ITEM = 'UPDATE_WISHLIST';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';
export const MOVE_WISHLIST_ITEM = 'MOVE_WISHLIST_ITEM';
