// INPUT TYPES
export const LOAD_INPUT = 'LOAD_INPUT';
export const UPDATE_INPUT = 'UPDATE_INPUT';

// AUTH TYPES
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';

// DATA TYPES
export const FETCH_DATA = 'FETCH_DATA';

// OVERVIEW TYPES
export const SET_OVERVIEW = 'SET_OVERVIEW';
export const UPDATE_OVERVIEW_DETAIL = 'UPDATE_OVERVIEW_DETAIL';

// WISHLIST TYPES
export const LOAD_WISHLIST = 'LOAD_WISHLIST';
export const ADD_WISHLIST_ITEM = 'UPDATE_WISHLIST';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';
export const MOVE_WISHLIST_ITEM = 'MOVE_WISHLIST_ITEM';
