import React from 'react';

export default React.createContext({
  vbucks: null,
  setVbucks: vbucks => {},
  dailies: null,
  setDailies: dailies => {},
  alerts: null,
  setAlerts: alerts => {},
  averageAlerts: null,
  setAverageAlerts: average => {},
  level: null,
  setLevel: level => {},
  experience: null,
  setExperience: xp => {},
  extraXP: null,
  setExtraXP: xp => {},
  unfinishedXP: null,
  setUnfinishedXP: xp => {},
  loginDay: null,
  setLoginDay: day => {},
  punchCardStates: null,
  setPunchCardStates: states => {},
  dailyBRStates: null,
  setDailyBRStates: states => {},
  dailySTWStates: null,
  setDailySTWStates: states => {},
  dailyAlertsStates: null,
  setDailyAlertsStates: states => {}
});
